# This file has been copied from: https://kodimensional.dev/posts/2019-02-25-haskell-travis
sudo: true
language: haskell

git:
  depth: 5

cabal: "2.4"

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:

  # Cabal
  - ghc: 8.4.4
  - ghc: 8.6.5
  - ghc: 8.8.3

  # Stack
  - ghc: 8.8.3
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"

install:
  - |
    if [ -z "$STACK_YAML" ]; then
      ghc --version
      cabal --version
      cabal new-update
      # cabal new-build --enable-tests --enable-benchmarks
      cabal new-build
    else
      # install stack
      curl -sSL https://get.haskellstack.org/ | sh

      # build project with stack
      stack --version
      # stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
      stack build --system-ghc
    fi

script:
  - |
    if [ -z "$STACK_YAML" ]; then
      # cabal new-test --enable-tests
      echo "Enable tests!"
    else
      # stack test --system-ghc
      echo "Enable tests!"
    fi

notifications:
  email: false

